using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ecoeden.Inventory.Infrastructure.Database.SQL.Migrations.StockDbContext
{
    /// <inheritdoc />
    public partial class SetsAutoGeneratedId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                schema: "ecoeden.stock",
                table: "ProductStocks",
                type: "uniqueidentifier",
                nullable: false,
                defaultValueSql: "NEWID()",
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                schema: "ecoeden.stock",
                table: "ProductStocks",
                type: "uniqueidentifier",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldDefaultValueSql: "NEWID()");
        }
    }
}
